-module(meru_transform).

-export([parse_transform/2]).

-import(erl_syntax, [
    attribute_name/1,
    attribute_arguments/1,
    list_elements/1,
    list/1,
    atom_value/1,
    tuple_elements/1,
    integer_value/1,
    binary_fields/1,
    binary_field_body/1,
    record_field_name/1,
    record_field_value/1
]).

-record(state, {
    record,
    records = orddict:new(),
    pool,
    bucket,
    old_pool,
    old_bucket,
    keyfun,
    mergefun,
    migratefun
}).

-define(RIAK, meru_riak).
-define(_FUNS, [{record_to_proplist, 1}, {proplist_to_record, 1}, {new, 0}, {new, 1},
                {put, 1}, {put, 2}, {delete, 1}, {delete, 2}]).
-define(FUNS, [{get, 1}, {get, 2}, {put_merge, 2}, {put_merge, 3}, {put_merge, 4} | ?_FUNS]).
-define(MIGRATE_FUNS, [{migrate_get, 1}, {migrate_get, 3}, {migrate_put_merge, 2},
                       {migrate_put_merge, 3}, {migrate_put_merge, 4}, {migrate_put_merge, 5} | ?_FUNS]).

parse_transform(Forms, Opts) ->
    % dbg:tracer(),
    % dbg:tpl(?MODULE,x),
    % dbg:p(all,[c]),
    Context = parse_trans:initial_context(Forms, Opts),
    State = parse_trans:do_inspect(fun inspect/4, #state{}, Forms, Context),
    Result = parse_trans:revert(no_auto_import(export_funs(add_funs(Forms, State, Context), State, Context), Context)),
    parse_trans:optionally_pretty_print(Result, Opts, Context),
    Result.

inspect(attribute, Form, _Context, Acc) ->
    case atom_value(attribute_name(Form)) of
        meru_migration ->
            {undefined, undefined, undefined} = {Acc#state.old_pool, Acc#state.old_bucket, Acc#state.migratefun},
            [OldPool, OldBucket, MigrateFunName] = tuple_elements(hd(attribute_arguments(Form))),
            {false, Acc#state{ old_pool = meru:pool_name(atom_value(OldPool)), old_bucket = parse_trans:revert_form(OldBucket), migratefun = atom_value(MigrateFunName) }};
        meru_pool ->
            undefined = Acc#state.pool,
            Pool0 = atom_value(hd(attribute_arguments(Form))),
            Pool = meru:pool_name(Pool0),
            {false, Acc#state{ pool = Pool }};
        meru_bucket ->
            undefined = Acc#state.bucket,
            BucketName = parse_trans:revert_form(hd(attribute_arguments(Form))),
            {false, Acc#state{ bucket = BucketName }};
        meru_keyfun ->
            undefined = Acc#state.keyfun,
            KeyFunName = atom_value(hd(attribute_arguments(Form))),
            {false, Acc#state{ keyfun = KeyFunName }};
        meru_mergefun ->
            undefined = Acc#state.mergefun,
            MergeFunName = atom_value(hd(attribute_arguments(Form))),
            {false, Acc#state{ mergefun = MergeFunName }};
        meru_record ->
            undefined = Acc#state.record,
            RecordName = atom_value(hd(attribute_arguments(Form))),
            {false, Acc#state{ record = RecordName }};
        record ->
            [Name, {_, _, _, Fields0}] = attribute_arguments(Form),
            Fields = parse_trans:revert_form(list([record_field_name(F) || F <- Fields0])),
            Values0 = [begin FV = record_field_value(F),
                if FV == none -> {atom, 1, undefined}; true -> FV end end || F <- Fields0],
            Values = parse_trans:revert_form(list(Values0)),
            {false, Acc#state{ records = orddict:store(atom_value(Name), {Fields, Values}, Acc#state.records) }};
        _ ->
            {false, Acc}
    end;
inspect(_, _, _, Acc) ->
    {false, Acc}.

add_funs(Forms, #state{ old_bucket = undefined, old_pool = undefined } = State, Context) ->
    do_add_funs(?FUNS, Forms, State, Context);
add_funs(Forms, State, Context) ->
    do_add_funs(?MIGRATE_FUNS, Forms, State, Context).

do_add_funs(Funs, Forms, State, Context) ->
    lists:foldl(fun (FunName, Acc) ->
        add_fun(FunName, Acc, State, Context)
    end, Forms, Funs).

add_fun({migrate_get, 1}, Forms, #state{ pool = Pool, old_pool = OldPool }, Context) ->
    Form = [{function,1,get,1,
     [{clause,32,
          [{var,32,'Key'}],
          [],
          [{call,33,
               {remote,33,{atom,33,?RIAK},{atom,33,multi_transaction}},
               [{atom,33,OldPool},
                {atom,33,Pool},
                {'fun',33,
                    {clauses,
                        [{clause,33,
                             [{var,33,'OldPid'},{var,33,'Pid'}],
                             [],
                             [{call,34,
                                  {atom,34,get},
                                  [{var,34,'OldPid'},
                                   {var,34,'Pid'},
                                   {var,34,'Key'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({migrate_get, 3}, Forms, #state{ bucket = BucketName, old_bucket = OldBucketName, keyfun = KeyFunName, migratefun = MigrateFunName }, Context) ->
    Form = [{function,1,get,3,
  [{clause,39,
    [{var,39,'OldPid'},{var,39,'Pid'},{var,39,'Key'}],
    [],
    [{'case',40,
      {call,40,
       {remote,40,{atom,40,?RIAK},{atom,40,get}},
       [{var,40,'Pid'},
        BucketName,
        {call,40,{atom,40,KeyFunName},[{var,40,'Key'}]}]},
      [{clause,41,
        [{tuple,41,[{atom,41,ok},{var,41,'RObj'}]}],
        [],
        [{tuple,42,
          [{atom,42,ok},
           {call,42,
            {atom,42,proplist_to_record},
            [{call,42,
              {atom,42,binary_to_term},
              [{call,42,
                {remote,42,{atom,42,riakc_obj},{atom,42,get_value}},
                [{var,42,'RObj'}]}]}]}]}]},
       {clause,43,
        [{tuple,43,[{atom,43,error},{atom,43,notfound}]}],
        [],
        [{'case',44,
          {call,44,
           {remote,44,{atom,44,?RIAK},{atom,44,get}},
           [{var,44,'OldPid'},
            OldBucketName,
            {call,44,{atom,44,KeyFunName},[{var,44,'Key'}]}]},
          [{clause,45,
            [{tuple,45,[{atom,45,ok},{var,45,'OldRObj'}]}],
            [],
            [{match,46,
              {var,46,'Rec'},
              {call,46,
               {atom,46,MigrateFunName},
               [{call,46,
                 {atom,46,proplist_to_record},
                 [{call,46,
                   {atom,46,binary_to_term},
                   [{call,46,
                     {remote,46,{atom,46,riakc_obj},{atom,46,get_value}},
                     [{var,46,'OldRObj'}]}]}]}]}},
             {call,47,{atom,47,put},[{var,47,'Pid'},{var,47,'Rec'}]},
             {tuple,48,[{atom,48,ok},{var,48,'Rec'}]}]},
           {clause,49,[{var,49,'OldError'}],[],[{var,50,'OldError'}]}]}]},
       {clause,52,[{var,52,'Error'}],[],[{var,53,'Error'}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({get, 1}, Forms, #state{ pool = Pool }, Context) ->
    Form = [{function,1,get,1,
     [{clause,32,
          [{var,32,'Key'}],
          [],
          [{call,33,
               {remote,33,{atom,33,?RIAK},{atom,33,transaction}},
               [{atom,33,Pool},
                {'fun',33,
                    {clauses,
                        [{clause,33,
                             [{var,33,'Pid'}],
                             [],
                             [{call,34,
                                  {atom,34,get},
                                  [{var,34,'Pid'},{var,34,'Key'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({get, 2}, Forms, #state{ bucket = BucketName, keyfun = KeyFunName }, Context) ->
    Form = [{function,1,get,2,
  [{clause,39,
    [{var,39,'Pid'},{var,39,'Key'}],
    [],
    [{'case',40,
      {call,40,
       {remote,40,{atom,40,?RIAK},{atom,40,get}},
       [{var,40,'Pid'},
        BucketName,
        {call,40,{atom,40,KeyFunName},[{var,40,'Key'}]}]},
      [{clause,41,
        [{tuple,41,[{atom,41,ok},{var,41,'RObj'}]}],
        [],
        [{tuple,42,
          [{atom,42,ok},
           {call,42,
            {atom,42,proplist_to_record},
            [{call,42,
              {atom,42,binary_to_term},
              [{call,42,
                {remote,42,{atom,42,riakc_obj},{atom,42,get_value}},
                [{var,42,'RObj'}]}]}]}]}]},
       {clause,43,[{var,43,'Error'}],[],[{var,44,'Error'}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({put, 1}, Forms, #state{ pool = Pool }, Context) ->
    Form = [{function,1,put,1,
     [{clause,49,
          [{var,49,'Record'}],
          [],
          [{call,50,
               {remote,50,{atom,50,?RIAK},{atom,50,transaction}},
               [{atom,50,Pool},
                {'fun',50,
                    {clauses,
                        [{clause,50,
                             [{var,50,'Pid'}],
                             [],
                             [{call,51,
                                  {atom,51,put},
                                  [{var,51,'Pid'},
                                   {var,51,'Record'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({put, 2}, Forms, #state{ bucket = BucketName, keyfun = KeyFunName }, Context) ->
    Form = [{function,1,put,2,
     [{clause,56,
          [{var,56,'Pid'},{var,56,'Record'}],
          [],
          [{match,57,
               {var,57,'Key'},
               {call,57,{atom,57,KeyFunName},[{var,57,'Record'}]}},
           {'case',58,
               {call,58,
                   {remote,58,{atom,58,?RIAK},{atom,58,put}},
                   [{var,58,'Pid'},
                    {call,58,
                        {remote,58,{atom,58,riakc_obj},{atom,58,new}},
                        [BucketName,
                         {var,58,'Key'},
                         {call,59,
                             {atom,59,term_to_binary},
                             [{call,59,
                                  {atom,59,record_to_proplist},
                                  [{var,59,'Record'}]}]}]}]},
               [{clause,60,
                    [{atom,60,ok}],
                    [],
                    [{tuple,60,
                         [{atom,60,ok},{var,60,'Key'},{var,60,'Record'}]}]},
                {clause,61,[{var,61,'Error'}],[],[{var,61,'Error'}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({put_merge, 2}, Forms, #state{ pool = Pool }, Context) ->
    Form = [{function,1,put_merge,2,
     [{clause,66,
          [{var,66,'Record'},{var,66,'Options'}],
          [],
          [{call,67,
               {remote,67,{atom,67,?RIAK},{atom,67,transaction}},
               [{atom,67,Pool},
                {'fun',67,
                    {clauses,
                        [{clause,67,
                             [{var,67,'Pid'}],
                             [],
                             [{call,68,
                                  {atom,68,put_merge},
                                  [{var,68,'Pid'},
                                   {var,68,'Record'},
                                   {var,68,'Options'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({put_merge, 3}, Forms, #state{ mergefun = MergeFunName, pool = Pool }, Context) ->
    Form = [{function,1,put_merge,3,
     [{clause,73,
          [{var,73,'Pid'},{var,73,'Record'},{var,73,'Options'}],
          [[{call,73,{atom,73,is_pid},[{var,73,'Pid'}]}]],
          [{'case',74,
               {call,74,{atom,74,get},[{var,74,'Pid'},{var,74,'Record'}]},
               [{clause,75,
                    [{tuple,75,[{atom,75,ok},{var,75,'OldRecord'}]}],
                    [],
                    [{call,75,
                         {atom,75,put},
                         [{var,75,'Pid'},
                          {call,75,
                              {atom,75,MergeFunName},
                              [{var,75,'OldRecord'},
                               {var,75,'Record'},
                               {var,75,'Options'}]}]}]},
                {clause,76,
                    [{var,76,'_Error'}],
                    [],
                    [{call,76,
                         {atom,76,put},
                         [{var,76,'Pid'},
                          {call,76,
                              {atom,76,MergeFunName},
                              [{atom,76,notfound},
                               {var,76,'Record'},
                               {var,76,'Options'}]}]}]}]}]},
      {clause,78,
          [{var,78,'Key'},{var,78,'Record'},{var,78,'Options'}],
          [],
          [{call,79,
               {remote,79,{atom,79,?RIAK},{atom,79,transaction}},
               [{atom,79,Pool},
                {'fun',79,
                    {clauses,
                        [{clause,79,
                             [{var,79,'Pid'}],
                             [],
                             [{call,80,
                                  {atom,80,put_merge},
                                  [{var,80,'Pid'},
                                   {var,80,'Key'},
                                   {var,80,'Record'},
                                   {var,80,'Options'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({put_merge, 4}, Forms, #state{ mergefun = MergeFunName }, Context) ->
    Form = [{function,1,put_merge,4,
     [{clause,85,
          [{var,85,'Pid'},{var,85,'Key'},{var,85,'Record'},{var,85,'Options'}],
          [],
          [{'case',86,
               {call,86,{atom,86,get},[{var,86,'Pid'},{var,86,'Key'}]},
               [{clause,87,
                    [{tuple,87,[{atom,87,ok},{var,87,'OldRecord'}]}],
                    [],
                    [{call,87,
                         {atom,87,put},
                         [{var,87,'Pid'},
                          {call,87,
                              {atom,87,MergeFunName},
                              [{var,87,'OldRecord'},
                               {var,87,'Record'},
                               {var,87,'Options'}]}]}]},
                {clause,88,
                    [{var,88,'_Error'}],
                    [],
                    [{call,88,
                         {atom,88,put},
                         [{var,88,'Pid'},
                          {call,88,
                              {atom,88,MergeFunName},
                              [{atom,88,notfound},
                               {var,88,'Record'},
                               {var,88,'Options'}]}]}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({migrate_put_merge, 2}, Forms, #state{ pool = Pool, old_pool = OldPool }, Context) ->
    Form = [{function,1,put_merge,2,
     [{clause,119,
          [{var,119,'Record'},{var,119,'Options'}],
          [],
          [{call,120,
               {remote,120,
                   {atom,120,?RIAK},
                   {atom,120,multi_transaction}},
               [{atom,120,OldPool},
                {atom,120,Pool},
                {'fun',120,
                    {clauses,
                        [{clause,120,
                             [{var,120,'OldPid'},{var,120,'Pid'}],
                             [],
                             [{call,121,
                                  {atom,121,put_merge},
                                  [{var,121,'OldPid'},
                                   {var,121,'Pid'},
                                   {var,121,'Record'},
                                   {var,121,'Options'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({migrate_put_merge, 3}, Forms, #state{ pool = Pool, old_pool = OldPool }, Context) ->
    Form = [{function,1,put_merge,3,
     [{clause,126,
          [{var,126,'Key'},{var,126,'Record'},{var,126,'Options'}],
          [],
          [{call,127,
               {remote,127,
                   {atom,127,?RIAK},
                   {atom,127,multi_transaction}},
               [{atom,127,OldPool},
                {atom,127,Pool},
                {'fun',127,
                    {clauses,
                        [{clause,127,
                             [{var,127,'OldPid'},{var,127,'Pid'}],
                             [],
                             [{call,128,
                                  {atom,128,put_merge},
                                  [{var,128,'OldPid'},
                                   {var,128,'Pid'},
                                   {var,128,'Key'},
                                   {var,128,'Record'},
                                   {var,128,'Options'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({migrate_put_merge, 4}, Forms, #state{ mergefun = MergeFunName }, Context) ->
    Form = [{function,1,put_merge,4,
     [{clause,133,
          [{var,133,'OldPid'},
           {var,133,'Pid'},
           {var,133,'Record'},
           {var,133,'Options'}],
          [[{op,133,'andalso',
                {call,133,{atom,133,is_pid},[{var,133,'OldPid'}]},
                {call,133,{atom,133,is_pid},[{var,133,'Pid'}]}}]],
          [{'case',134,
               {call,134,
                   {atom,134,get},
                   [{var,134,'OldPid'},{var,134,'Pid'},{var,134,'Record'}]},
               [{clause,135,
                    [{tuple,135,[{atom,135,ok},{var,135,'OldRecord'}]}],
                    [],
                    [{call,135,
                         {atom,135,put},
                         [{var,135,'Pid'},
                          {call,135,
                              {atom,135,MergeFunName},
                              [{var,135,'OldRecord'},
                               {var,135,'Record'},
                               {var,135,'Options'}]}]}]},
                {clause,136,
                    [{var,136,'_Error'}],
                    [],
                    [{call,136,
                         {atom,136,put},
                         [{var,136,'Pid'},
                          {call,136,
                              {atom,136,MergeFunName},
                              [{atom,136,notfound},
                               {var,136,'Record'},
                               {var,136,'Options'}]}]}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({migrate_put_merge, 5}, Forms, #state{ mergefun = MergeFunName }, Context) ->
    Form = [{function,1,put_merge,5,
     [{clause,141,
          [{var,141,'OldPid'},
           {var,141,'Pid'},
           {var,141,'Key'},
           {var,141,'Record'},
           {var,141,'Options'}],
          [],
          [{'case',142,
               {call,142,
                   {atom,142,get},
                   [{var,142,'OldPid'},{var,142,'Pid'},{var,142,'Key'}]},
               [{clause,143,
                    [{tuple,143,[{atom,143,ok},{var,143,'OldRecord'}]}],
                    [],
                    [{call,143,
                         {atom,143,put},
                         [{var,143,'Pid'},
                          {call,143,
                              {atom,143,MergeFunName},
                              [{var,143,'OldRecord'},
                               {var,143,'Record'},
                               {var,143,'Options'}]}]}]},
                {clause,144,
                    [{var,144,'_Error'}],
                    [],
                    [{call,144,
                         {atom,144,put},
                         [{var,144,'Pid'},
                          {call,144,
                              {atom,144,MergeFunName},
                              [{atom,144,notfound},
                               {var,144,'Record'},
                               {var,144,'Options'}]}]}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({delete, 1}, Forms, #state{ pool = Pool }, Context) ->
    Form = [{function,1,delete,1,
     [{clause,93,
          [{var,93,'Record'}],
          [],
          [{call,94,
               {remote,94,{atom,94,?RIAK},{atom,94,transaction}},
               [{atom,94,Pool},
                {'fun',94,
                    {clauses,
                        [{clause,94,
                             [{var,94,'Pid'}],
                             [],
                             [{call,95,
                                  {atom,95,delete},
                                  [{var,95,'Pid'},
                                   {var,95,'Record'}]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({delete, 2}, Forms, #state{ bucket = BucketName, keyfun = KeyFunName }, Context) ->
    Form = [{function,1,delete,2,
     [{clause,100,
          [{var,100,'Pid'},{var,100,'Record'}],
          [],
          [{match,101,
               {var,101,'Key'},
               {call,101,{atom,101,KeyFunName},[{var,101,'Record'}]}},
           {'case',102,
               {call,102,
                   {remote,102,{atom,102,?RIAK},{atom,102,delete}},
                   [{var,102,'Pid'},
                    BucketName,
                    {var,102,'Key'}]},
               [{clause,103,
                    [{atom,103,ok}],
                    [],
                    [{tuple,103,[{atom,103,ok},{var,103,'Key'}]}]},
                {clause,104,[{var,104,'Error'}],[],[{var,104,'Error'}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({record_to_proplist, 1}, Forms, #state{ record = RecordName, records = Records }, Context) ->
    {RecordFields, _} = orddict:fetch(RecordName, Records),
    Form = [{function,1,record_to_proplist,1,
         [{clause,17,
              [{var,17,'Record'}],
              [],
              [{call,18,
                   {remote,18,{atom,18,lists},{atom,18,zip}},
                   [RecordFields,
                    {call,18,
                        {atom,18,tl},
                        [{call,18,
                             {atom,18,tuple_to_list},
                             [{var,18,'Record'}]}]}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({proplist_to_record, 1}, Forms, #state{ record = RecordName, records = Records }, Context) ->
    {RecordFields, RecordValues} = orddict:fetch(RecordName, Records),
    Form = [{function,1,proplist_to_record,1,
      [{clause,7,
        [{var,7,'Proplist'}],
        [],
        [{call,8,
          {atom,8,list_to_tuple},
          [{cons,9,
            {atom,9,RecordName},
            {call,10,
             {remote,10,{atom,10,lists},{atom,10,reverse}},
             [{call,11,
               {remote,11,{atom,11,lists},{atom,11,foldl}},
               [{'fun',11,
                 {clauses,
                  [{clause,11,
                    [{tuple,11,[{var,11,'K'},{var,11,'Default'}]},{var,11,'Acc'}],
                    [],
                    [{cons,12,
                      {call,12,
                       {remote,12,{atom,12,proplists},{atom,12,get_value}},
                       [{var,12,'K'},{var,12,'Proplist'},{var,12,'Default'}]},
                      {var,12,'Acc'}}]}]}},
                {nil,13},
                {call,13,
                 {remote,13,{atom,13,lists},{atom,13,zip}},
                 [RecordFields,
                  RecordValues]}]}]}}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({new, 0}, Forms, _State, Context) ->
    Form = [{function,1,new,0,[{clause,22,[],[],[{call,23,{atom,23,new},[{nil,23}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context);
add_fun({new, 1}, Forms, _State, Context) ->
    Form = [{function,1,new,1,
           [{clause,27,
                    [{var,27,'Proplist'}],
                    [],
                    [{call,28,
                           {atom,28,proplist_to_record},
                           [{var,28,'Proplist'}]}]}]}],
    parse_trans:do_insert_forms(above, Form, Forms, Context).

export_funs(Forms, #state{ old_pool = undefined, old_bucket = undefined }, Context) ->
    Exports = [{attribute, 1, export, ?FUNS}],
    parse_trans:do_insert_forms(above, Exports, Forms, Context);
export_funs(Forms, _State, Context) ->
    MigrateFuns = lists:map(fun (F) ->
                                    case F of
                                        {migrate_get, A}       -> {get, A};
                                        {migrate_put_merge, A} -> {put_merge, A};
                                        O                      -> O
                                    end
                            end, ?MIGRATE_FUNS),
    Exports = [{attribute, 1, export, MigrateFuns}],
    parse_trans:do_insert_forms(above, Exports, Forms, Context).

no_auto_import(Forms, Context) ->
    NoAuto = [{attribute, 1, compile, {no_auto_import, [{get, 1}, {put, 2}]}}],
    parse_trans:do_insert_forms(above, NoAuto, Forms, Context).
